version: '3.8'

services:
  mysqldb:
    image: mysql:8.0
    container_name: mysqldb_sccom
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sccom-test
      MYSQL_USER: user
      MYSQL_PASSWORD: password-test
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: